name: GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
            go-version: '1.14.1'
      - name: Setup gom2h
        run: |
          GO111MODULE=off GOBIN=$(pwd)/bin go get github.com/matsuyoshi30/gom2h/cmd/gom2h
          bin/gom2h _md/.
      - uses: actions/checkout@master
      - name: Build
        run: mv _md/*.html ./docs/